const APP_SUBTITLE = "SYFC Volunteers"
const INPUT_STAFF_USERNAME_PLACEHOLDER = "Staff Username"
const INPUT_EMAIL_PLACEHOLDER = "Email address"
const INPUT_PASSWORD_PLACEHOLDER = "Password"
const INPUT_RMBME = "Remember Me"
const BUTTON_LOGIN = "Login"
const LINK_FORGOT_PW = "Forgot Password"
const LINK_NUSNET_LOGIN = "Login with NUSNET"
const COPYRIGHT_TEXT = "Copyright &copy; 2020 MiniMetrics"

export default {
  APP_SUBTITLE,
  INPUT_STAFF_USERNAME_PLACEHOLDER,
  INPUT_EMAIL_PLACEHOLDER,
  INPUT_PASSWORD_PLACEHOLDER,
  INPUT_RMBME,
  BUTTON_LOGIN,
  LINK_FORGOT_PW,
  LINK_NUSNET_LOGIN,
  COPYRIGHT_TEXT,
}
