const CREATE_FORM_TITLE_NAME = 'Full Name'
const CREATE_FORM_TITLE_EMAIL = 'Email Address'
const CREATE_FORM_TITLE_PW = 'Password'
const CREATE_FORM_TITLE_DOB = 'Date of Birth'
const CREATE_FORM_TITLE_NRIC = 'NRIC No.'
const CREATE_FORM_TITLE_ADDRESS = 'Address'
const CREATE_FORM_TITLE_POSTAL_CODE = 'Postal Code'
const CREATE_FORM_TITLE_CHURCH = 'Church'
const CREATE_FORM_TITLE_DEPT = 'Department'
const CREATE_FORM_TITLE_GENDER = 'Gender'
const CREATE_FORM_TITLE_NUMBER = 'Phone Number'

export default {
  CREATE_FORM_TITLE_NAME,
  CREATE_FORM_TITLE_EMAIL,
  CREATE_FORM_TITLE_PW,
  CREATE_FORM_TITLE_DOB,
  CREATE_FORM_TITLE_NRIC,
  CREATE_FORM_TITLE_ADDRESS,
  CREATE_FORM_TITLE_POSTAL_CODE,
  CREATE_FORM_TITLE_CHURCH,
  CREATE_FORM_TITLE_DEPT,
  CREATE_FORM_TITLE_GENDER,
  CREATE_FORM_TITLE_NUMBER,
}
