const CREATE_FORM_TITLE_NAME = 'Full Name'
const CREATE_FORM_TITLE_EMAIL = 'Email Address'
const CREATE_FORM_TITLE_NRIC = 'NRIC No.'
const CREATE_FORM_TITLE_GENDER = 'Gender'
const CREATE_FORM_TITLE_DOB = 'Date of Birth'
const CREATE_FORM_TITLE_DEPT = 'Department'

export default {
  CREATE_FORM_TITLE_NAME,
  CREATE_FORM_TITLE_EMAIL,
  CREATE_FORM_TITLE_NRIC,
  CREATE_FORM_TITLE_GENDER,
  CREATE_FORM_TITLE_DOB,
  CREATE_FORM_TITLE_DEPT,
}
