export const EVENTS_EDIT_LOAD_EVENT = "EVENTS_EDIT_LOAD_EVENT"

export const EVENTS_EDIT_CHANGE_TITLE = "EVENTS_EDIT_CHANGE_TITLE"
export const EVENTS_EDIT_CHANGE_DATES = "EVENTS_EDIT_CHANGE_DATES"
export const EVENTS_EDIT_CHANGE_DESC = "EVENTS_EDIT_CHANGE_DESC"
export const EVENTS_EDIT_DISCARD = "EVENTS_EDIT_DISCARD"

export const EVENTS_EDIT_SUBMIT_START = "EVENTS_EDIT_SUBMIT_START"
export const EVENTS_EDIT_SUBMIT_SUCCESS = "EVENTS_EDIT_SUBMIT_SUCCESS"
export const EVENTS_EDIT_SUBMIT_FAILURE = "EVENTS_EDIT_SUBMIT_FAILURE"
export const EVENTS_DELETE_START = "EVENTS_DELETE_START"
export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS"
export const EVENTS_DELETE_FAILURE = "EVENTS_DELETE_FAILURE"
export const EVENTS_EDIT_RESET_NOTIFICATION = "EVENTS_EDIT_RESET_NOTIFICATION"
