export const JOIN_EVENTS_JOIN_START = "JOIN_EVENTS_JOIN_START"
export const JOIN_EVENTS_JOIN_SUCCESS = "JOIN_EVENTS_JOIN_SUCCESS"
export const JOIN_EVENTS_JOIN_FAILURE = "JOIN_EVENTS_JOIN_FAILURE"

export const JOIN_EVENTS_VIEW_EVENT = "JOIN_EVENTS_VIEW_EVENT"
export const JOIN_EVENTS_CLOSE_VIEW = "JOIN_EVENTS_CLOSE_VIEW"
export const JOIN_EVENTS_RESET_NOTIFICATION = "JOIN_EVENTS_RESET_NOTIFICATION"
