export const LOGIN_VOLUNTEER_CHANGE_EMAIL = "LOGIN_VOLUNTEER_CHANGE_EMAIL"
export const LOGIN_VOLUNTEER_CHANGE_PASSWORD = "LOGIN_VOLUNTEER_CHANGE_PASSWORD"
export const LOGIN_VOLUNTEER_RESET = "LOGIN_VOLUNTEER_RESET"

export const LOGIN_VOLUNTEER_LOGIN_START = "LOGIN_VOLUNTEER_LOGIN_START"
export const LOGIN_VOLUNTEER_LOGIN_SUCCESS = "LOGIN_VOLUNTEER_LOGIN_SUCCESS"
export const LOGIN_VOLUNTEER_LOGIN_FAILURE = "LOGIN_VOLUNTEER_LOGIN_FAILURE"
export const LOGIN_VOLUNTEER_RESET_NOTIFICATION = "LOGIN_VOLUNTEER_RESET_NOTIFICATION"
