export const LOGIN_STAFF_CHANGE_USERNAME = "LOGIN_STAFF_CHANGE_USERNAME"
export const LOGIN_STAFF_CHANGE_PASSWORD = "LOGIN_STAFF_CHANGE_PASSWORD"
export const LOGIN_STAFF_RESET = "LOGIN_STAFF_RESET"

export const LOGIN_STAFF_LOGIN_START = "LOGIN_STAFF_LOGIN_START"
export const LOGIN_STAFF_LOGIN_SUCCESS = "LOGIN_STAFF_LOGIN_SUCCESS"
export const LOGIN_STAFF_LOGIN_FAILURE = "LOGIN_STAFF_LOGIN_FAILURE"
export const LOGIN_STAFF_RESET_NOTIFICATION = "LOGIN_STAFF_RESET_NOTIFICATION"
