export const MY_EVENTS_LOAD_START = "MY_EVENTS_LOAD_START"
export const MY_EVENTS_LOAD_SUCCESS = "MY_EVENTS_LOAD_SUCCESS"
export const MY_EVENTS_LOAD_FAILURE = "MY_EVENTS_LOAD_FAILURE"

export const MY_EVENTS_VIEW_EVENT = "MY_EVENTS_VIEW_EVENT"
export const MY_EVENTS_CLOSE_VIEW = "MY_EVENTS_CLOSE_VIEW"
