export const PROFILE_CHANGE_PW_CHANGE_OLD_PW = "PROFILE_CHANGE_PW_CHANGE_OLD_PW"
export const PROFILE_CHANGE_PW_CHANGE_NEW_PW = "PROFILE_CHANGE_PW_CHANGE_NEW_PW"
export const PROFILE_CHANGE_PW_CHANGE_CNFM_PW = "PROFILE_CHANGE_PW_CHANGE_CNFM_PW"
export const PROFILE_CHANGE_PW_DISCARD = "PROFILE_CHANGE_PW_DISCARD"

export const PROFILE_CHANGE_PW_START = "PROFILE_CHANGE_PW_START"
export const PROFILE_CHANGE_PW_SUCCESS = "PROFILE_CHANGE_PW_SUCCESS"
export const PROFILE_CHANGE_PW_FAILURE = "PROFILE_CHANGE_PW_FAILURE"
export const PROFILE_CHANGE_PW_RESET_NOTIFICATION = "PROFILE_CHANGE_PW_RESET_NOTIFICATION"
