export const STAFF_CHANGE_PW_CHANGE_OLD_PW = "STAFF_CHANGE_PW_CHANGE_OLD_PW"
export const STAFF_CHANGE_PW_CHANGE_NEW_PW = "STAFF_CHANGE_PW_CHANGE_NEW_PW"
export const STAFF_CHANGE_PW_CHANGE_CNFM_PW = "STAFF_CHANGE_PW_CHANGE_CNFM_PW"
export const STAFF_CHANGE_PW_DISCARD = "STAFF_CHANGE_PW_DISCARD"

export const STAFF_CHANGE_PW_START = "STAFF_CHANGE_PW_START"
export const STAFF_CHANGE_PW_SUCCESS = "STAFF_CHANGE_PW_SUCCESS"
export const STAFF_CHANGE_PW_FAILURE = "STAFF_CHANGE_PW_FAILURE"
export const STAFF_CHANGE_PW_RESET_NOTIFICATION = "STAFF_CHANGE_PW_RESET_NOTIFICATION"
